[package]
name = "rmatrix"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bench"
path = "benches/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.139"

[dev-dependencies]
criterion = "0.5.1"
ndarray = "0.16.1"
